### ISSUE TITLE
IB::Contract in ib-extensions has different superclass (Object) than ib-api

### ISSUE THREAD

**Issue by pelly** [ib-ruby/ib-extensions#7]
`IB::Contract` defined in 
https://github.com/ib-ruby/ib-extensions/blob/master/lib/ib/models/contract.rb
has `Object` as it's superclass (since it doesn't extend any class explicitly)

But `IB::Contract` defined in 
https://github.com/ib-ruby/ib-api/blob/master/lib/models/ib/contract.rb
has `IB::Model` as its superclass.

As a result, requiring both of these files will cause a mismatched superclass exception:

```
/home/user/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/ib-api-972.5/lib/models/ib/contract.rb:14:in `<module:IB>': superclass mismatch for class Contract (TypeError)
	from /home/user/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/ib-api-972.5/lib/models/ib/contract.rb:6:in `<top (required)>'
	from <internal:/home/user/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from <internal:/home/user/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
```

**Comment by topofocus** [comment]
Hi,
the contract class in ib-extensions reopens IB::Contract defined in ib-api. 

As ib-extensions depends on ib-api, IB::Contract should always been initialized before the model-file in ib-extensions is parsed. 

How do you initialize ib-extensions?

**Comment by pelly** [comment]
I'm trying to bring in technical-analysis which I think brings in
ib-extensions.

I've run into issues like this before. I believe this bug surfaces
depending on how the filesystem lays out files - different ordering for
different OS installs (even different linux distros). So sometimes
requiring technical-analysis will bring in ib-extensions'
"ib/model/contract" before ib-api's  "models/ib/contract".

An easier (while also still robust) way would be to ensure that
ib-extensions' "ib/model/contract.rb" file requires
ib-api's "models/ib/contract". I can submit a PR for that if you prefer.

**Comment by topofocus** [comment]
Thanks for bringing this to my attention.
You are right, its considered as bad practice to reopen classes across ruby-gems.

A proper solution would to use mixins and include/prepend them later.

That would translate in a change of the design of ib-extensions.

Your opinion?

**Comment by pelly** [comment]
That sounds reasonable to me.

In general the thing that is extending a class has to know about that class
and ensure that it is initialized correctly in a certain state. So I always
like to ensure I've required the original "base" class that I'm reopening /
extending.
